# Generated by Django 5.1.2 on 2024-11-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_menuitem_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
