# Generated by Django 5.1.2 on 2024-11-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_section_delete_card_slider_select_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='select_section',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
