# Generated by Django 5.1.2 on 2024-11-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_slider_select_section_delete_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='select_section',
            field=models.CharField(choices=[('product', 'product'), ('banner', 'banner')], default='home', max_length=20),
        ),
    ]
