# Generated by Django 5.1.2 on 2024-11-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_slider_select_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
