# Generated by Django 5.1.2 on 2024-11-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_menuitem_image_menuitemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
        migrations.DeleteModel(
            name='MenuItemImage',
        ),
    ]
