# Generated by Django 5.1.2 on 2024-11-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_menuitem_image_delete_menuitemimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images/')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(max_length=100)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('select_section', models.CharField(choices=[('1', 'Banner section 1'), ('2', 'Banner section 2'), ('3', 'Banner section 3'), ('4', 'Banner section 4')], default='home', max_length=20)),
            ],
        ),
    ]
