# Generated by Django 5.1.2 on 2024-11-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='slider',
            name='button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
