# Generated by Django 5.1.2 on 2024-11-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_menuitem_order_alter_slider_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
